### ISSUE TITLE
Error, check you internet connection [SSL peer certificate or SSH remote key was not OK]

### ISSUE THREAD

**Issue by cobraalloc** [0x000N3X4N/anonfile#5]
An error message appears when you try to upload a simple file:

> Error, check you internet connection [SSL peer certificate or SSH remote key was not OK]

[http://dl4.joxi.net/drive/2020/01/25/0038/1256/2520296/96/89e81c93ac.jpg](url)
![image](https://user-images.githubusercontent.com/38838465/73126540-0ac4d380-3fc5-11ea-929b-0e5eba3d89cb.png)

**Comment by 0gecco** [comment]
No fix? It doesn't work here either.

**Comment by cobraalloc** [comment]
I started researching this issue. Currently can't reproduce the same error, but found another problems which may be derived from this issue. I will try to fix anothe problem in scope of this work item.
![image](https://user-images.githubusercontent.com/38838465/86532505-45675c00-bed3-11ea-8d74-b7eec6b25dc2.png)

**Comment by cobraalloc** [comment]
Reproduced on linux release binaries:
![image](https://user-images.githubusercontent.com/38838465/86532977-bd596600-be82-11ea-9a3b-3c33da289e0b.png)

**Comment by cobraalloc** [comment]
Look like already fixed in non stable version from **master** branch.

**Comment by cobraalloc** [comment]
Fixed in v1.0.0.
https://github.com/0x000N3X4N/anonfile/releases/tag/v1.0.0
