### ISSUE TITLE
[Suggestion] Ability to Upload File from Direct-Link

### ISSUE THREAD

**Issue by MC874** [0x000N3X4N/anonfile#7]
# Suggestion
H!
I've my archived project from another File-Cloud and i want to import the assets to AnonFiles as Archive. It's really not efficient to download the assets first to my internal storage and upload it to AnonFiles/BayFile. I'm hoping to see a feature that can give ability to fetch stream data from a direct-link and immediately upload it to AnonFiles/BayFile without the files being saved first to disk.

# Implementation
anonfile.exe --direct-url <direct-url>
anonfile.exe -U <https://direct-link/file.zip>

**Comment by cobraalloc** [comment]
Hello, @MC874 !
Thanks for your suggestion, but there are a few ambiguities.
First of all as i can see according [anonfiles API](https://anonfiles.com/docs/api) there is no function to upload part of file content, **only whole file with content**. **This means that whole file binary stream will be stored in RAM and it is unacceptable for big files(Max available file size is 20GB)**.

Second point is, we need to know that another File-Cloud provide public API to:
- fetch whole binary stream(content) divided by chunks of file
- get total file size (in B, KB, etc..)

Without such requirements this feature is **impossible**.

**Comment by MC874** [comment]
Hi!
Thank you for the fast response!
1) I didn't expect that AnonFiles API would be very limited, hence i think it wouldn't possible without involving VPS server.
2) I'm hosting my project on Cloudflare Workers and it is indeed has API Key, but probably we can't move forward without point 1.
3) Probably an Alternative idea is to download the file as temp-file and once it's already uploaded to Anonfiles, it would delete automaticly. Thus would very help with my storage.

**Comment by cobraalloc** [comment]
Hello!
1-2. Unfortunately, I don't see any ways to involve hosted VPS server for this project.
3. If i'm not wrong it can be done using sample bash/bat script with curl.
Download files by direct link using curl(if no any authorization required):
`curl -O https://cdn-133.anonfiles.com/77Je07J9xa/22da3137-1645474570/hello_world.txt`
then upload to anonfile:
`anonfile.exe <your_path_to_file>`
and
`del hello_world.txt`
